In [5]:
import numpy as np

In [9]:
b = np.random.randint(20, 80, size=(8, 9))
print(b)

[[54 49 24 47 41 62 32 32 28]
 [74 21 20 38 58 21 75 52 24]
 [72 70 23 44 55 70 69 39 63]
 [66 66 21 45 30 20 68 55 64]
 [75 36 72 73 38 28 68 49 58]
 [70 33 68 66 31 42 69 30 67]
 [28 48 67 43 61 39 74 68 47]
 [44 24 23 64 61 28 69 70 57]]


In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [10]:
b[2:6]

array([[72, 70, 23, 44, 55, 70, 69, 39, 63],
       [66, 66, 21, 45, 30, 20, 68, 55, 64],
       [75, 36, 72, 73, 38, 28, 68, 49, 58],
       [70, 33, 68, 66, 31, 42, 69, 30, 67]])

In [11]:
b[1:5,1:6]

array([[21, 20, 38, 58, 21],
       [70, 23, 44, 55, 70],
       [66, 21, 45, 30, 20],
       [36, 72, 73, 38, 28]])

In [14]:
import pandas as pd

In [32]:
k=['[4,7]','[2,9]','[7,3]','[90,50]']
k

['[4,7]', '[2,9]', '[7,3]', '[90,50]']

In [33]:
np.array(k)

array(['[4,7]', '[2,9]', '[7,3]', '[90,50]'], dtype='<U7')

In [34]:
pd.Series(k)

0      [4,7]
1      [2,9]
2      [7,3]
3    [90,50]
dtype: object

In [35]:
pd.DataFrame(k,columns=['name,'sub'],index=[289,290,291])

SyntaxError: unterminated string literal (detected at line 1) (4090599676.py, line 1)

In [27]:
t=[4,7,2,9,7,3,90,50]
t

[4, 7, 2, 9, 7, 3, 90, 50]

In [28]:
np.array(t)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [29]:
pd.Series(t)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64