In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [6]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit_transform(df['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [11]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [23]:
df['embarked'].unique()

array([0, 1, 2], dtype=int64)

In [24]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['embarked']=lb.fit_transform(df['species'])

In [25]:
df['embarked'].unique()

array([0, 1, 2], dtype=int64)

In [26]:
df['embarked']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: embarked, Length: 150, dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
 5   embark        150 non-null    int64  
 6   embarked      150 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 8.3 KB


In [31]:
df

sepal_length  sepal_width  petal_length  petal_width  species  embark  \
0             5.1          3.5           1.4          0.2        0       0   
1             4.9          3.0           1.4          0.2        0       0   
2             4.7          3.2           1.3          0.2        0       0   
3             4.6          3.1           1.5          0.2        0       0   
4             5.0          3.6           1.4          0.2        0       0   
..            ...          ...           ...          ...      ...     ...   
145           6.7          3.0           5.2          2.3        2       2   
146           6.3          2.5           5.0          1.9        2       2   
147           6.5          3.0           5.2          2.0        2       2   
148           6.2          3.4           5.4          2.3        2       2   
149           5.9          3.0           5.1          1.8        2       2   

     embarked  
0           0  
1           0  
2           0  
3           0  
4           0  
..        ...  
145         2  
146         2  
147         2  
148         2  
149         2  

[150 rows x 7 columns]

In [33]:
df['species'].unique()

array([0, 1, 2], dtype=int64)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [27]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
 df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [29]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [34]:
oh_species=pd.get_dummies(df['species'])
df=pd.concat([df.drop('species',axis=1),oh_species],axis=1)

In [35]:
df

sepal_length  sepal_width  petal_length  petal_width  setosa  versicolor  \
0             5.1          3.5           1.4          0.2    True       False   
1             4.9          3.0           1.4          0.2    True       False   
2             4.7          3.2           1.3          0.2    True       False   
3             4.6          3.1           1.5          0.2    True       False   
4             5.0          3.6           1.4          0.2    True       False   
..            ...          ...           ...          ...     ...         ...   
145           6.7          3.0           5.2          2.3   False       False   
146           6.3          2.5           5.0          1.9   False       False   
147           6.5          3.0           5.2          2.0   False       False   
148           6.2          3.4           5.4          2.3   False       False   
149           5.9          3.0           5.1          1.8   False       False   

     virginica  
0        False  
1        False  
2        False  
3        False  
4        False  
..         ...  
145       True  
146       True  
147       True  
148       True  
149       True  

[150 rows x 7 columns]